version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"  # Usa la variable de entorno para el puerto
    depends_on:
      - backend
    networks:
      frontend-backend-network:
        ipv4_address: ${FRONTEND_IP}  # Usa la variable de entorno para la IP

  db:
    build:
      context: ./database
    volumes:
      - ./db/data:/var/lib/sqlite
    networks:
      backend-db-network:
        ipv4_address: ${DB_IP}  # Usa la variable de entorno para la IP
    command: >
      sh -c "sqlite3 /var/lib/sqlite/app.db < /init.sql && tail -f /dev/null"

  backend:
    build: ./backend
    volumes:
      - ./db/data:/var/lib/sqlite
    depends_on:
      - db
    networks:
      frontend-backend-network:
        ipv4_address: ${BACKEND_IP}  # Usa la variable de entorno para la IP
      backend-db-network:
        ipv4_address: ${BACKEND_DB_IP}  # Usa la variable de entorno para la IP

networks:
  frontend-backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24

  backend-db-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
